[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 250000

; ESP-IDF 5.x für pulse_cnt Support
platform_packages = 
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.0.0
    platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/arduino-esp32/releases/download/3.0.0/esp32-arduino-libs-3.0.0.zip

lib_deps = 
    bblanchon/ArduinoJson @ ^7.4.2
    fastled/FastLED @ ^3.10.3
    bodmer/TFT_eSPI @ ^2.5.43

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DARDUINO_RUNNING_CORE=1
    -DESP32
    -DUSER_SETUP_LOADED=1 
    -include lib/TFT_eSPI_Setup/User_Setup.h
